sudo: required

language: generic

services:
  - docker

before_installa:
  - echo "start Createing an image with dockerfile"
  - docker build -t alsdud154/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true alsdud154/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success!"